### ISSUE TITLE
Configuration names with spaces causes react-native-xcode.sh to error out.

### ISSUE THREAD

**Issue by corymsmith** [Thinkmill/react-native-schemes-manager#10]
### Steps to reproduce the behavior
1.) Create a configuration named Staging Debug and add to package.json entry.
2.) Run fix-xcode script and fix-libraries.
3.) Build and run app

### Expected behavior
No errors when running script

### Actual behavior

Receiving error messages like this in the XCode build log and the rest of the script fails so the app doesn't get set up correctly to use the xip IP addresses and will only load from the pre-packaged bundle.

```
../node_modules/react-native-schemes-manager/lib/react-native-xcode.sh: eval: line 37: syntax error near unexpected token `Debug'
../node_modules/react-native-schemes-manager/lib/react-native-xcode.sh: eval: line 37: `  Staging Debug|Debug)'
```

It's due to how this is being eval'ed here: https://github.com/Thinkmill/react-native-schemes-manager/blob/master/lib/react-native-xcode.sh#L17 so maybe we have to escape with double quotes?

**Comment by corymsmith** [comment]
I fixed the other issue related to spaces in names with #3 so I think once this ones sorted it should be all good.

**Comment by blargity** [comment]
Thanks @corymsmith, I'll go ahead and close this issue.
