### ISSUE TITLE
add in --sourcemap-output  ?

### ISSUE THREAD

**Issue by JasonMore** [Thinkmill/react-native-schemes-manager#14]
Any chance at adding in sourcemap into the build?

```
$NODE_BINARY "$REACT_NATIVE_DIR/local-cli/cli.js" bundle \
  --entry-file "$ENTRY_FILE" \
  --platform ios \
  --dev $DEV \
  --reset-cache \
  --bundle-output "$BUNDLE_FILE" \
  --assets-dest "$DEST"
  --sourcemap-output "$DEST/main.jsbundle.map"
```

I'm not sure if there are any implications for having it on all the time. Any thoughts?

**Comment by blargity** [comment]
I think the main thing I'd want to do is mirror whatever the Debug scheme does with the copied schemes. Does the Debug scheme generate sourcemaps? I haven't tested thoroughly, but from memory I tried to just get the schemes that were Debug that weren't named `Debug` to be treated as if they were for the rest of the RN build process.

That's a lot of words and context for: Sure I'd be happy to if that's what vanilla React Native does with the Debug scheme.

**Comment by JasonMore** [comment]
Sure that makes sense. I don't think it does by default. No worries thanks for the thoughts.
