### ISSUE TITLE
zsh: command not found: react-native-schemes-manager

### ISSUE THREAD

**Issue by AlmogRnD** [Thinkmill/react-native-schemes-manager#22]
Getting the following error when running via terminal 

zsh: command not found: react-native-schemes-manager

**Comment by mamaz** [comment]
I encountered this as well:

```
yarn
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
$ react-native-schemes-manager all
sh: react-native-schemes-manager: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by blargity** [comment]
It looks like this is something around how `npm` / `yarn` run scripts, paths, and such. Do other `package.json` scripts work for you when they reference scripts that are installed in your `node_modules` folder? For example if `babel-cli` works then this should work too.

This might be relevant: https://stackoverflow.com/questions/36106817/unable-to-run-babel-via-npm-script-babel-command-not-found

Does that help at all?

**Comment by AlmogRnD** [comment]
Yes all other packages do work

**Comment by mamaz** [comment]
It turns out to be my fault, NODE_ENV is set to production in my case, so devDependencies is not installed.

**Comment by blargity** [comment]
That'd make sense. @AlmogRnD are you still experiencing the issue?

**Comment by AlmogRnD** [comment]
@blargity I removed the package, couldn't use it because of this issue

**Comment by blargity** [comment]
Fair enough. I haven't been able to replicate the issue, but I'll leave it open until we can with high confidence say that it's not related to the package or it isn't happening anymore.

**Comment by blargity** [comment]
I'll go ahead and close this issue. If it happens to someone else we can reopen.

**Comment by export-mike** [comment]
Happened to me 👍 it had NODE_ENV set to production for that current bash session. Hope your well! @thekevinbrown :)

**Comment by thekevinbrown** [comment]
I'm great, hope you're well too @export-mike!
