### ISSUE TITLE
Error! RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andreyslyusar** [Thinkmill/react-native-schemes-manager#23]
```$ react-native-schemes-manager all``` failed ``` ⃠ [fix-script]: Error! RangeError: Maximum call stack size exceeded```
```
$ yarn install
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
$ react-native-schemes-manager all
Hiding schemes from node_modules xcode projects.
 ⃠ [fix-script]: Error! RangeError: Maximum call stack size exceeded
...
```

It seems project schemes config correctly, but what can be a source of the issue?

**Comment by blargity** [comment]
That's really odd. Any chance you could make a reproduction case so I can dig deeper into the issue?

**Comment by andreyslyusar** [comment]
I somehow manage to fix the mistake and cannot reproduce it anymore. Should we close an issue in this case and reopen in case it is reproducible?

**Comment by blargity** [comment]
Yeah, I think that's the best course of action here. Thanks for reporting it so we have a record that it was a problem.
