### ISSUE TITLE
No option to pass in a config script for the bundler

### ISSUE THREAD

**Issue by BrandonSmith** [Thinkmill/react-native-schemes-manager#45]
### Steps to reproduce the behavior
`react-native-xcode.sh` from `react-native` allows passing in a configuration script for the metro bundler as follows:

`export BUNDLE_CONFIG=<path to rn-cli-config.js>`

### Expected behavior

Developer should be able to specify a bundler configuration script.

### Actual behavior

No option available.

**Comment by blargity** [comment]
Has this been resolved with the release of #46?
